import { env } from "cloudflare:workers";
import { revalidatePath } from "next/cache";
import { getChatGPTUser, chatGPTSignInPath } from "./chatgpt-auth";
import { Home, Search, UserRound, PenLine, Trash2 } from "lucide-react";
export const dynamic = "force-dynamic";
function db() { if (!env.DB) throw new Error("Database unavailable"); return env.DB; }
type Person = { id:string; name:string; handle:string; bio:string };
type Post = { id:string; author_id:string; body:string; created_at:number; name:string; handle:string };
async function ensureUser(user: NonNullable<Awaited<ReturnType<typeof getChatGPTUser>>>) {
  const existing = await db().prepare("SELECT id FROM users WHERE id=?").bind(user.userId).first();
  if (!existing) { const base=user.email.split("@")[0].toLowerCase().replace(/[^a-z0-9_]/g,"").slice(0,18)||"user"; await db().prepare("INSERT OR IGNORE INTO users (id,name,handle,bio,created_at) VALUES (?,?,?,?,?)").bind(user.userId,user.fullName||base,`${base}_${crypto.randomUUID().slice(0,5)}`,"",Date.now()).run(); }
}
async function publish(form:FormData) { "use server"; const user=await getChatGPTUser(); if(!user)return; const body=String(form.get("body")||"").trim(); if(!body||body.length>280)return; await ensureUser(user); await db().prepare("INSERT INTO posts (id,author_id,body,created_at) VALUES (?,?,?,?)").bind(crypto.randomUUID(),user.userId,body,Date.now()).run(); revalidatePath("/"); }
async function remove(form:FormData) { "use server"; const user=await getChatGPTUser(); if(!user)return; await db().prepare("DELETE FROM posts WHERE id=? AND author_id=?").bind(String(form.get("id")),user.userId).run(); revalidatePath("/"); }
async function toggleFollow(form:FormData) { "use server"; const user=await getChatGPTUser(); if(!user)return; const target=String(form.get("target")||""); if(target===user.userId)return; await ensureUser(user); const found=await db().prepare("SELECT id FROM users WHERE id=?").bind(target).first(); if(!found)return; const existing=await db().prepare("SELECT 1 FROM follows WHERE follower_id=? AND following_id=?").bind(user.userId,target).first(); if(existing)await db().prepare("DELETE FROM follows WHERE follower_id=? AND following_id=?").bind(user.userId,target).run(); else await db().prepare("INSERT INTO follows (follower_id,following_id) VALUES (?,?)").bind(user.userId,target).run(); revalidatePath("/"); }
async function saveProfile(form:FormData) { "use server"; const user=await getChatGPTUser(); if(!user)return; const name=String(form.get("name")||"").trim().slice(0,40),bio=String(form.get("bio")||"").trim().slice(0,160); if(!name)return; await db().prepare("UPDATE users SET name=?,bio=? WHERE id=?").bind(name,bio,user.userId).run(); revalidatePath("/"); }
function Avatar({name}:{name:string}) { return <span className="avatar" aria-hidden="true">{name.slice(0,1).toUpperCase()}</span> }
export default async function Page({searchParams}:{searchParams:Promise<{view?:string;q?:string;user?:string}>}) {
 const auth=await getChatGPTUser(); if(!auth)return <main className="welcome"><div className="welcome-card"><div className="logo">t<span>.</span></div><h1>いまの気持ちを、ひと言から。</h1><p>投稿して、気になる人をフォロー。新しい順に会話を追えます。</p><a className="primary-button" href={chatGPTSignInPath("/")} target="_top">ChatGPTでログイン</a></div></main>;
 try { await ensureUser(auth); const {view="home",q="",user:profileId}=await searchParams;
 const me=await db().prepare("SELECT id,name,handle,bio FROM users WHERE id=?").bind(auth.userId).first<Person>();
 const profile=profileId?await db().prepare("SELECT id,name,handle,bio FROM users WHERE id=?").bind(profileId).first<Person>():me;
 const posts=view==="search"?[]:(view==="profile"?await db().prepare("SELECT p.*,u.name,u.handle FROM posts p JOIN users u ON u.id=p.author_id WHERE p.author_id=? ORDER BY p.created_at DESC LIMIT 50").bind(profile?.id||"").all<Post>():await db().prepare("SELECT p.*,u.name,u.handle FROM posts p JOIN users u ON u.id=p.author_id WHERE p.author_id=? OR p.author_id IN (SELECT following_id FROM follows WHERE follower_id=?) ORDER BY p.created_at DESC LIMIT 50").bind(auth.userId,auth.userId).all<Post>()).results;
 const people=view==="search"&&q.trim()?(await db().prepare("SELECT id,name,handle,bio FROM users WHERE (name LIKE ? OR handle LIKE ?) AND id!=? ORDER BY name LIMIT 30").bind(`%${q.trim().slice(0,40)}%`,`%${q.trim().slice(0,40)}%`,auth.userId).all<Person>()).results:[];
 const followed=(await db().prepare("SELECT following_id FROM follows WHERE follower_id=?").bind(auth.userId).all<{following_id:string}>()).results.map(r=>r.following_id);
 return <div className="shell"><aside className="sidebar"><a className="logo" href="/" aria-label="ホーム">t<span>.</span></a><nav aria-label="メイン"><a className={view==="home"?"active":""} href="/"><Home size={22}/><span>ホーム</span></a><a className={view==="search"?"active":""} href="/?view=search"><Search size={22}/><span>ユーザー検索</span></a><a className={view==="profile"?"active":""} href={`/?view=profile&user=${encodeURIComponent(auth.userId)}`}><UserRound size={22}/><span>プロフィール</span></a></nav><div className="sidebar-me"><Avatar name={me?.name||"U"}/><div><strong>{me?.name}</strong><small>@{me?.handle}</small></div></div></aside><main className="timeline"><header className="page-header"><h1>{view==="search"?"ユーザー検索":view==="profile"?"プロフィール":"ホーム"}</h1><span>{view==="home"?"フォロー中の投稿":""}</span></header>
 {view==="home"&&<form action={publish} className="composer"><Avatar name={me?.name||"U"}/><div><label htmlFor="body" className="sr-only">投稿内容</label><textarea id="body" name="body" placeholder="いま、何を考えている？" maxLength={280} required/><div className="compose-footer"><span>280文字まで</span><button className="primary-button" type="submit"><PenLine size={16}/>投稿する</button></div></div></form>}
 {view==="search"&&<><form className="search-form" action="/"><input type="hidden" name="view" value="search"/><Search size={20}/><input name="q" defaultValue={q} placeholder="名前またはユーザーIDで検索" aria-label="ユーザー検索"/><button type="submit">検索</button></form>{q.trim()?people.length?people.map(p=><div className="person-row" key={p.id}><Avatar name={p.name}/><div className="person-info"><a href={`/?view=profile&user=${encodeURIComponent(p.id)}`}><strong>{p.name}</strong></a><small>@{p.handle}</small>{p.bio&&<p>{p.bio}</p>}</div><form action={toggleFollow}><input type="hidden" name="target" value={p.id}/><button className="follow-button" type="submit">{followed.includes(p.id)?"フォロー解除":"フォロー"}</button></form></div>):<div className="empty">該当するユーザーは見つかりませんでした。</div>:<div className="empty">名前やユーザーIDを入力して探してください。</div>}</>}
 {view==="profile"&&(profile?<div className="profile"><div className="profile-banner"/><div className="profile-body"><Avatar name={profile.name}/>{profile.id!==auth.userId&&<form action={toggleFollow}><input type="hidden" name="target" value={profile.id}/><button className="follow-button" type="submit">{followed.includes(profile.id)?"フォロー解除":"フォロー"}</button></form>}<h2>{profile.name}</h2><small>@{profile.handle}</small>{profile.bio&&<p>{profile.bio}</p>}{profile.id===auth.userId&&<form action={saveProfile} className="edit-profile"><label>表示名<input name="name" defaultValue={profile.name} maxLength={40} required/></label><label>自己紹介<input name="bio" defaultValue={profile.bio} maxLength={160} placeholder="自己紹介を入力"/></label><button type="submit">プロフィールを保存</button></form>}</div><h3 className="section-title">投稿</h3></div>:<div className="empty">ユーザーが見つかりません。</div>)}
 {view!=="search"&&(posts.length?posts.map(post=><article className="post" key={post.id}><Avatar name={post.name}/><div className="post-main"><div className="post-heading"><a href={`/?view=profile&user=${encodeURIComponent(post.author_id)}`}><strong>{post.name}</strong></a><span>@{post.handle} · {new Intl.DateTimeFormat("ja-JP",{dateStyle:"medium",timeStyle:"short"}).format(post.created_at)}</span></div><p>{post.body}</p>{post.author_id===auth.userId&&<form action={remove}><input type="hidden" name="id" value={post.id}/><button type="submit" className="delete-button" aria-label="投稿を削除" title="投稿を削除"><Trash2 size={17}/></button></form>}</div></article>):<div className="empty">{view==="profile"?"まだ投稿がありません。":"まだ投稿がありません。最初の投稿をしてみましょう。"}</div>)}
 </main><aside className="right-rail"><div className="rail-card"><h2>シンプルにつながる</h2><p>フォローした人の投稿が、新しい順にホームへ表示されます。</p><a href="/?view=search">ユーザーを探す →</a></div></aside></div>;
 } catch(error) { console.error("Feed unavailable",error); return <main className="welcome"><div className="welcome-card"><h1>読み込めませんでした</h1><p>少し時間をおいて、もう一度お試しください。</p><a className="primary-button" href="/">再読み込み</a></div></main> }
}
