import test from 'node:test';
import assert from 'node:assert/strict';
import {initialLedger,register,operate,marketView,DAY} from './share-engine.mjs';
test('multiple classes preserve existing shares and enforce aggregate issuance and split caps',()=>{
 const s=setup();
 call(s,'alice',{action:'issue',asset:'alice-class',name:'Original',quantity:100});
 const create={action:'create_class',asset:'alice-common',name:'Second',quantity:200,requestId:'new-class-operation-001'};
 operate(s,'alice',create);operate(s,'alice',create);
 const id='alice-class-new-class-operation-001';
 assert.equal(s.assets[id].supply,200);
 assert.equal(s.assets['alice-class'].supply,100);
 assert.equal(Object.values(s.assets).filter(a=>a.owner==='alice' && a.kind==='class').length,2);
 assert.throws(()=>call(s,'bob',{...create,requestId:'other-owner-operation-001'}),/owner/);
 assert.throws(()=>call(s,'alice',{action:'create_class',name:'Overflow',quantity:367}),/class_limit/);
 call(s,'alice',{action:'request',asset:id,ratio:2,mode:'solo'});
 const p=s.assets[id].proposal,ref={asset:id,proposalId:p.id,round:1};
 assert.equal(s.assets['alice-class'].proposal,null);
 call(s,'alice',{action:'vote',choice:'yes',...ref});
 call(s,'alice',{action:'execute',...ref},DAY);
 assert.equal(s.assets[id].price,50);assert.equal(s.assets[id].holders.alice,400);
 assert.equal(s.assets['alice-class'].price,100);assert.equal(s.assets['alice-class'].holders.alice,100);
 assert.throws(()=>call(s,'alice',{action:'issue',asset:'alice-class',name:'Original',quantity:167}),/class_limit/);
 const restored=JSON.parse(JSON.stringify(s));
 assert.equal(marketView(restored,'alice').assets.find(a=>a.id===id).classTotal,500);
});
test('split execution rechecks capacity after another class issues shares',()=>{
 const s=setup();
 call(s,'alice',{action:'issue',asset:'alice-class',name:'Original',quantity:200});
 call(s,'alice',{action:'request',asset:'alice-class',ratio:2,mode:'solo'});
 const p=s.assets['alice-class'].proposal,ref={asset:'alice-class',proposalId:p.id,round:1};
 call(s,'alice',{action:'vote',choice:'yes',...ref});
 call(s,'alice',{action:'create_class',name:'Other',quantity:300});
 assert.throws(()=>call(s,'alice',{action:'execute',...ref},DAY),/split_cap/);
 assert.equal(s.assets['alice-class'].supply,200);
});
test('only the creator can burn their own class shares and voting locks supply',()=>{
 const s=setup();
 call(s,'alice',{action:'issue',asset:'alice-class',name:'Class',quantity:100});
 assert.throws(()=>call(s,'bob',{action:'burn',asset:'alice-class',quantity:1}),/owner/);
 assert.throws(()=>call(s,'alice',{action:'burn',asset:'alice-class',quantity:101}),/burn_holdings/);
 const marketCapBefore=s.assets['alice-class'].price*s.assets['alice-class'].supply;
 call(s,'alice',{action:'burn',asset:'alice-class',quantity:40});
 assert.equal(s.assets['alice-class'].supply,60);
 assert.equal(s.assets['alice-class'].holders.alice,60);
 assert.equal(s.assets['alice-class'].price,marketCapBefore/60);
 assert.equal(s.assets['alice-class'].price*s.assets['alice-class'].supply,marketCapBefore);
 assert.throws(()=>call(s,'alice',{action:'burn',asset:'alice-class',quantity:60}),/burn_holdings/);
 call(s,'alice',{action:'request',asset:'alice-class',ratio:2,mode:'solo'});
 assert.throws(()=>call(s,'alice',{action:'burn',asset:'alice-class',quantity:1}),/proposal_active/);
});
let serial=0;
const call=(s,uid,op,now=0)=>operate(s,uid,{requestId:`test-operation-${String(++serial).padStart(8,'0')}`,asset:'alice-common',...op},now);
const setup=()=>{const s=initialLedger(); for(const id of ['alice','bob','carol'])register(s,id,{name:id}); return s;};
test('identity, creator-only issuance, branding and class cap',()=>{
 const s=setup();
 assert.throws(()=>call(s,'bob',{action:'issue',asset:'alice-class',name:'Brand',quantity:10}),/owner/);
 call(s,'alice',{action:'issue',asset:'alice-class',name:'Brand',quantity:600});
 assert.equal(s.assets['alice-class'].holders.alice,600);
 assert.throws(()=>call(s,'alice',{action:'issue',asset:'alice-class',name:'Brand',quantity:67}),/class_limit/);
 assert.throws(()=>call(s,'alice',{action:'brand',asset:'alice-class',name:'Brand',image:'javascript:alert(1)'}),/image/);
});
test('global availability, points and idempotency',()=>{
 const s=setup(); s.members.alice.balance=1e6; s.members.bob.balance=1e6;
 for(let i=0;i<10;i++)call(s,'alice',{action:'trade',quantity:100,side:'buy'});
 assert.throws(()=>call(s,'bob',{action:'trade',quantity:1,side:'buy'}),/supply/);
 const op={action:'trade',asset:'alice-common',quantity:1,side:'sell',requestId:'idempotent-operation-123'};
 operate(s,'alice',op);operate(s,'alice',op);
 assert.equal(s.assets['alice-common'].holders.alice,999);
 assert.equal(marketView(s,'bob').assets.find(a=>a.id==='alice-common').available,1);
});
test('buying raises price, selling lowers it, and a round trip creates no points',()=>{
 const s=setup(); s.members.alice.balance=1e6;
 const startBalance=s.members.alice.balance,startPrice=s.assets['alice-common'].price;
 call(s,'alice',{action:'trade',quantity:50,side:'buy'});
 assert.ok(s.assets['alice-common'].price>startPrice);
 const peak=s.assets['alice-common'].price;
 call(s,'alice',{action:'trade',quantity:50,side:'sell'});
 assert.ok(s.assets['alice-common'].price<peak);
 assert.ok(Math.abs(s.assets['alice-common'].price-startPrice)<1e-10);
 assert.ok(Math.abs(s.members.alice.balance-startBalance)<1e-8);
 assert.equal(s.members.alice.history[0].beforePrice,peak);
});
test('trades crossing or leaving the five-percent line become public disclosures',()=>{
 const s=setup(); s.members.alice.balance=1e12;
 call(s,'alice',{action:'trade',quantity:50,side:'buy'},500);
 assert.equal(s.disclosures.length,0);
 call(s,'alice',{action:'trade',quantity:50,side:'sell'},600);
 s.assets['alice-common'].price=1000000;
 call(s,'alice',{action:'trade',quantity:49,side:'buy'},1000);
 assert.equal(s.disclosures.length,0);
 call(s,'alice',{action:'trade',quantity:1,side:'buy'},2000);
 assert.equal(s.disclosures.length,1);
 assert.equal(s.disclosures[0].beforeShares,49);
 assert.equal(s.disclosures[0].afterShares,50);
 assert.equal(s.disclosures[0].afterRatio,0.05);
 assert.ok(s.disclosures[0].afterMarketCap>=1000000000);
 call(s,'alice',{action:'trade',quantity:1,side:'sell'},3000);
 assert.equal(s.disclosures.length,2);
 assert.equal(s.disclosures[0].beforeRatio,0.05);
 assert.equal(s.disclosures[0].afterShares,49);
 const publicView=marketView(s,'bob');
 assert.equal(publicView.disclosures.length,2);
 assert.equal(publicView.disclosures[0].traderName,'alice');
});
test('new proposals require one percent individually and snapshot prevents double voting',()=>{
 const s=setup();
 call(s,'alice',{action:'trade',quantity:10,side:'buy'});call(s,'bob',{action:'trade',quantity:1,side:'buy'});
 assert.throws(()=>call(s,'alice',{action:'request',ratio:2,mode:'joint'}),/request/);
 assert.throws(()=>call(s,'bob',{action:'request',ratio:2,mode:'solo'}),/request_power/);
 call(s,'alice',{action:'request',ratio:2,mode:'solo'});
 const p=s.assets['alice-common'].proposal;
 const ref={proposalId:p.id,round:1};
 assert.equal(p.status,'voting');
 call(s,'alice',{action:'vote',choice:'yes',...ref});
 call(s,'alice',{action:'trade',quantity:10,side:'sell'});
 call(s,'bob',{action:'trade',quantity:10,side:'buy'});
 call(s,'bob',{action:'vote',choice:'yes',...ref});
 assert.equal(p.yes,11);
 assert.throws(()=>call(s,'bob',{action:'vote',choice:'yes',...ref}),/voted/);
});
test('split needs closed majority vote, changes all holders and price, leaves class independent',()=>{
 const s=setup(); call(s,'alice',{action:'trade',quantity:10,side:'buy'});call(s,'bob',{action:'trade',quantity:1,side:'buy'});
 call(s,'alice',{action:'issue',asset:'alice-class',name:'Class',quantity:100});
 s.assets['alice-common'].price=2000;
 call(s,'alice',{action:'request',ratio:200,mode:'solo'});
 const p=s.assets['alice-common'].proposal;const ref={proposalId:p.id,round:1};
 call(s,'alice',{action:'vote',choice:'yes',...ref});call(s,'bob',{action:'vote',choice:'no',...ref});
 assert.throws(()=>call(s,'alice',{action:'execute',...ref}),/not_closed/);
 const priceBeforeSplit=s.assets['alice-common'].price;
 call(s,'bob',{action:'execute',...ref},DAY);
 const a=s.assets['alice-common'];assert.equal(a.supply,200000);assert.equal(a.price,priceBeforeSplit/200);assert.equal(a.holders.bob,200);
 assert.equal(s.assets['alice-class'].supply,100);assert.equal(s.assets['alice-class'].price,100);
 assert.throws(()=>call(s,'alice',{action:'execute',...ref},DAY),/not_closed/);
});
test('split keeps one share unit at 10 points or more and rechecks at execution',()=>{
 const s=setup();call(s,'alice',{action:'trade',quantity:10,side:'buy'});
 const a=s.assets['alice-common'];a.price=100;
 assert.throws(()=>call(s,'alice',{action:'request',ratio:11,mode:'solo'}),/split_price_floor/);
 call(s,'alice',{action:'request',ratio:10,mode:'solo'});
 const p=a.proposal,ref={proposalId:p.id,round:1};
 call(s,'alice',{action:'vote',choice:'yes',...ref});
 a.price=99;
 assert.throws(()=>call(s,'alice',{action:'execute',...ref},DAY),/split_price_floor/);
 assert.equal(a.supply,1000);assert.equal(a.price,99);
});
test('unit-size vote is separate, burns odd lots, and sets the minimum trade quantity',()=>{
 const s=setup();s.members.alice.balance=1e6;s.members.bob.balance=1e6;
 call(s,'alice',{action:'trade',quantity:10,side:'buy'});call(s,'bob',{action:'trade',quantity:7,side:'buy'});
 const a=s.assets['alice-common'],marketCap=a.price*a.supply;
 call(s,'alice',{action:'request_lot',lotSize:6,mode:'solo'});
 const p=a.proposal,ref={proposalId:p.id,round:1};
 assert.equal(p.kind,'lot');assert.equal(p.lotSize,6);assert.equal(p.ratio,undefined);
 call(s,'alice',{action:'vote',choice:'yes',...ref});call(s,'alice',{action:'execute',...ref},DAY);
 assert.equal(a.lotSize,6);assert.equal(a.holders.alice,6);assert.equal(a.holders.bob,6);
 assert.equal(a.supply,995);assert.equal(p.burned,5);
 assert.ok(Math.abs(a.price*a.supply-marketCap)<1e-8);
 assert.throws(()=>call(s,'alice',{action:'trade',quantity:1,side:'buy'}),/quantity/);
 call(s,'alice',{action:'trade',quantity:6,side:'buy'});
});
test('class split and revote have independent authority and one revote per proposal',()=>{
 const s=setup();call(s,'alice',{action:'issue',asset:'alice-class',name:'Class',quantity:100});
 call(s,'alice',{action:'request',asset:'alice-class',ratio:2,mode:'solo'});
 const p=s.assets['alice-class'].proposal; const ref={asset:'alice-class',proposalId:p.id,round:1};
 assert.throws(()=>call(s,'bob',{action:'vote',choice:'yes',...ref}),/not_holder/);
 call(s,'alice',{action:'vote',choice:'yes',...ref});
 call(s,'alice',{action:'revote',...ref});
 assert.equal(p.round,2);assert.equal(p.yes,0);
 assert.throws(()=>call(s,'alice',{action:'vote',choice:'yes',...ref}),/stale/);
 call(s,'alice',{action:'vote',choice:'yes',...ref,round:2});
 assert.throws(()=>call(s,'alice',{action:'revote',...ref,round:2}),/revote/);
 call(s,'alice',{action:'execute',...ref,round:2},DAY);
 assert.equal(s.assets['alice-class'].supply,200);assert.equal(s.assets['alice-class'].price,50);
 assert.equal(s.assets['alice-common'].supply,1000);assert.equal(s.assets['alice-common'].price,100);
});
test('ties are rejected; top holders and ballot data are separated by asset',()=>{
 const s=setup();for(const id of ['alice','bob'])call(s,id,{action:'trade',quantity:10,side:'buy'});
 call(s,'alice',{action:'request',ratio:2,mode:'solo'});const p=s.assets['alice-common'].proposal;const ref={proposalId:p.id,round:1};
 call(s,'alice',{action:'vote',choice:'yes',...ref});call(s,'bob',{action:'vote',choice:'no',...ref});call(s,'alice',{action:'execute',...ref},DAY);
 assert.equal(p.status,'rejected');assert.equal(s.assets['alice-common'].supply,1000);
 const v=marketView(s,'bob');assert.equal(v.assets.find(a=>a.id==='alice-class').leaders.length,0);
 assert.equal(v.assets.find(a=>a.id==='alice-common').proposal.choice,'no');
 assert.equal(JSON.stringify(v).includes('snapshot'),false);
});
test('holder distribution returns the top 10 and combines everyone else',()=>{
 const s=initialLedger();
 register(s,'owner',{name:'owner'});
 for(let i=0;i<22;i++) {
   const id=`holder${i}`; register(s,id,{name:`Holder ${i}`});
 }
 const target=s.assets['owner-common'];
 for(let i=0;i<22;i++) {
   const id=`holder${i}`;
   operate(s,id,{requestId:`distribution-${String(i).padStart(8,'0')}`,asset:target.id,action:'trade',quantity:1,side:'buy'});
 }
 const view=marketView(s,'owner').assets.find(a=>a.id===target.id);
 assert.equal(view.leaders.length,10);
 assert.equal(view.totalHeld,22);
 assert.equal(view.otherShares,12);
});
